name: versioning

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  versioning:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: Version Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
